from typing import List
from abc import ABC, abstractmethod

from domain.models import UserRequestDto

class DatabaseRequestService(ABC):
    """Contract that describes how user requests must be stored and retrieved."""

    @abstractmethod
    def create_request(self, user_id:str, session_id:str, search_term:str, data:dict) -> UserRequestDto:
        """Persist a new request generated by a user.

        Args:
            user_id: Identifier of the request owner.
            session_id: Identifier of the conversational session.
            search_term: User detected search request.
            data: Arbitrary payload captured for the request.

        Returns:
            The stored request with all persisted metadata.
        """
        pass

    @abstractmethod
    def get_requests(self, user_id:str, session_id:str) -> List[UserRequestDto]:
        """Retrieve all requests for a user in the specified session.

        Args:
            user_id: Identifier of the request owner.
            session_id: Identifier of the conversational session to inspect.

        Returns:
            Ordered collection of previously stored requests.
        """
        pass

    @abstractmethod
    def update_request(self, request:UserRequestDto):
        """Apply updates to a previously stored request instance.

        Args:
            request: Updated representation that must be persisted.
        """
        pass
